---
title: |
  | MATH 4502 - Statistics for Process Control
  | Homework 5 - Methods of Statistical Process Control
author: "Pranav Singh"
date: "03/08/2017"
output: pdf_document
ouptut:
  pdf_document:
  toc: yes
toc_depth: 2
---

```{r setup, echo = F}
library(knitr)
opts_chunk$set(cache = T)
opts_chunk$set(tidy = T, tidy.opts=list(width.cutoff = 80))
```

# 5.1
### What are chance and assignable causes of variability? What part do they play in the operation and interpretation of a Shewhart control chart?

Chance causes are an inherent part of the process; they represent natural variability or "background noise" and are the cumulative effect of many small, essentially unavoidable causes. A process that is operating with only chance causes of variation present is said to be in statistical control. 

Sources of variability that are not part of the chance cause pattern are referred to as assignable causes of variation. These are generally large in comparison to background noise, and it usually represents an unacceptable level of process performance. Assignable causes usually arise from three sources: improperly djusted or controlled machines, operator errors, or defective materials. A process that is operating in thee presence of assignable causes is said to be an out-of-control process.

Shewhart control charts are used to monitor and improve a process. Specifically, they can be used to detect assignable causes that are likely to be present when their plotted item is outside the chart's control limits. Management, operator, and engineering actions can subsequently be employed to eliminate the assignable causes found.

# 5.3
### Discuss type I and type II errors relative to the control chart. What practical implication in terms of process operation do these two types of errors have?

A type I error occurs when a point falls outside the control limits of a control chart, indicating an out-of-control condition when no assignable cause is really present. Type I errors can be minimized by widening the control limits, but that in turn increases the risk of a type II error. A type II error occurs when a point falls between the control limits when the process is really out of control.

# 5.7
### What are warning limits on a control chart? How can they be used?

# 5.8
### Discuss the rational subgroup concept. What part does it play in control chart analysis?

# 5.20
### Consider the control chart shown in Exercise 5.17. Would the use of warning limits reveal any potential out-of-control conditions?

# 5.22
### Sketch warning limits on the control chart in Exercise 5.19. Do these limits indicate any potential out-of-control conditions?

# 5.23
### Apply the Western Electric rules to the control chart presented in Exercise 5.19. Would these rules result in any out-of-control signals?

# 5.24
### Consider the time-varying process behavior shown below and on the next page. Match each of these several patterns of process performance to the corresponding x and R charts shown in figures (a) to (e) below.

# 5.25
### You consistently arrive at your office about one-half hour later than you would like. Develop a cause-and-effect diagram that identifies and outlines the possible causes of this event.

# 5.28
### Construct a cause-and-effect diagram that identifies the possible causes of consistently bad coffee from a large-capacity office coffee pot.

# 5.31
### The magnificent seven can be used in our personal lives. Develop a check sheet to record “defects” you have in your personal life (such as overeating, being rude, not meeting commitments, missing class, etc.). Use the check sheet to keep a record of these “defects” for one month. Use a Pareto chart to analyze these data. What are the underlying causes of these “defects”?
